POST https://magic-backend.onrender.com/formlist
Content-type: application/json

{
    "department": "Teste",
    "email": "teste@email.com",
    "message": "Essa eh uma mensagem",
    "name": "Teste da Silva",
    "company_name": "Teste Company",
    "segment": "Teste Segmento",
    "solution": "Teste Solucao",
    "phone": "999999999"
}

###

GET https://magic-backend.onrender.com/formlist

### 

DELETE https://magic-backend.onrender.com/formlist/17d73ccc-ce1c-4eaa-99c4-4c6894efc248